server:
  port: 8081

spring:
  datasource:
    name: test1
    url: jdbc:mysql://localhost:3306/microservice?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

