server:
  port: 8081

spring:
  application:
    name: User-Service
  datasource:
    name: test1
    url: jdbc:mysql://localhost:3306/microservice?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  #spring security okta as client
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-75927992.okta.com/oauth2/default
      client:
        registration:
          userServiceClient:
            provider: okta
            authorizationGrantType: client_credentials
            scope:
              - internal
            clientId: 0oa9z2zro0TWYfRdq5d7
            clientSecret: c_jkQFQmKWbmFkun1hyJQTrQH1u28Bj5XEElhk_e
        provider:
          okta:
            issuerUri: https://dev-75927992.okta.com/oauth2/default


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka

#actuator configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#reselience configuration

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventCosumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        waitDuration: 5

  ratelimiter:
    instances:
      ratingHotelLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 2s

#oka configutation
okta:
  oauth2:
    issuer: https://dev-75927992.okta.com/oauth2/default
    audience: api://default






